version: '3.8'
services:
  worker:
    build:
      context: worker
      target: dev
    tty: true
    init: true
    volumes:
      - ./.aws:/root/.aws
      - ./worker:/app
    env_file:
      - .env
  deploy:
    build: .
    tty: true
    init: true
    volumes:
      - ./.aws:/home/node/.aws
      - .:/app
    env_file:
      - .env
